sonar.projectKey=tpatrouillat_tokease
sonar.organization=tpatrouillat
sonar.projectName=tokease

sonar.sources=.
sonar.inclusions=tracker.py,setup.py
sonar.python.version=3.10,3.11,3.12,3.13

sonar.exclusions=docs/**,venv/**,build/**,dist/**,assets/**

sonar.sourceEncoding=UTF-8
